id: phq9
name: "PHQ-9 – depresia"
version: "1.0.0"
license:
  name: "Free to use (PHQ family)"
  url: "https://www.phqscreeners.com/"
recall: "Za posledné 2 týždne, do akej miery vás trápili nasledovné problémy?"
scale:
  labels: ["Vôbec nie", "Niekoľko dní", "Viac ako polovicu dní", "Takmer každý deň"]
  scores: [0, 1, 2, 3]
max_score: 27
cutoffs:
  - { range: [0, 4],   level: "Žiadna/minimálna", advice: "Sledovať stav." }
  - { range: [5, 9],   level: "Mierna",           advice: "Psychohygiena, preventívna konzultácia." }
  - { range: [10, 14], level: "Stredná",          advice: "Vhodná odborná konzultácia." }
  - { range: [15, 19], level: "Stredne ťažká",    advice: "Odporúčané odborné vyšetrenie a terapia." }
  - { range: [20, 27], level: "Ťažká",            advice: "Urgentne vyhľadajte odbornú pomoc." }
impairment_scale: ["Žiadny", "Mierny", "Výrazný", "Extrémny"]
safety_rules:
  - id: "self_harm"
    when: { item_id: "Q9", min_score: 1 }
    message: "Označené myšlienky na ublíženie si alebo smrť. V prípade ohrozenia volajte 112."
