id: gad7
name: "GAD-7 – úzkosť"
version: "1.0.0"
license:
  name: "Free to use (GAD-7 family)"
  url: "https://www.phqscreeners.com/"
recall: "Za posledné 2 týždne, do akej miery vás trápili nasledovné problémy?"
scale:
  labels: ["Vôbec nie", "Niekoľko dní", "Viac ako polovicu dní", "Takmer každý deň"]
  scores: [0, 1, 2, 3]
max_score: 21
cutoffs:
  - { range: [0, 4],   level: "Minimálna", advice: "Normálne stresové reakcie; psychohygiena." }
  - { range: [5, 9],   level: "Mierna",    advice: "Sledovať; relaxačné techniky zvládania stresu." }
  - { range: [10, 14], level: "Stredná",   advice: "Vhodná odborná konzultácia; zvažovať intervenciu." }
  - { range: [15, 21], level: "Ťažká",     advice: "Odporúčaná odborná diagnostika a terapia." }
impairment_scale: ["Žiadny", "Mierny", "Výrazný", "Extrémny"]
