id: gdt
name: General Distress Test
version: "1.0"
lang: sk

recall: "Za posledných 7 dní zvoľte, ako často sa vás týkali nasledujúce tvrdenia."

scale:
  labels: ["nikdy", "zriedka", "niekedy", "často"]
  scores: [0, 1, 2, 3]
  bands:
    - { label: "nízka záťaž",   min: 0,  max: 5 }
    - { label: "mierna záťaž",  min: 6,  max: 11 }
    - { label: "vysoká záťaž",  min: 12, max: 18 }

impairment_scale: ["vôbec nie", "trochu", "dosť", "veľmi"]
max_score: 18

cutoffs:
  - range: [0, 5]
    level: "nízka"
    advice: "Priebežné sledovanie, psychohygiena."

  - range: [6, 11]
    level: "mierna"
    advice: "Zvážte krátku konzultáciu a úpravu návykov."

  - range: [12, 18]
    level: "vysoká"
    advice: "Odporúčaná konzultácia s psychológom."

safety_rules: []
render:
  start_template: "gdt_form.html"
  result_template: "gdt_result.html"
