id: gdt
name: Gaming Disorder Test (GDT)
version: "1.0"
lang: sk

# Inštrukcia presne podľa dotazníka
recall: "Nižšie uvedené otázky sa týkajú vašej hernej aktivity za posledných 12 mesiacov. Prosím, uveďte, ako často sa v priemere vyskytli nasledujúce situácie."

scale:
  labels: ["nikdy", "zriedkavo", "niekedy", "často", "veľmi často"]
  scores: [0, 1, 2, 3, 4]
  # Heuristické pásma pre UI (ak chceš, neskôr upravíme podľa validovaných prahov)
  bands:
    - { label: "nízka miera symptómov",    min: 0,  max: 5 }
    - { label: "stredná miera symptómov",  min: 6,  max: 11 }
    - { label: "zvýšená miera symptómov",  min: 12, max: 16 }

# GDT nemá povinný funkčný dopad – vypneme ho (nebude sa zobrazovať)
impairment_scale: []

# 4 položky × max 4 body = 16
max_score: 16

# Loader vyžaduje cutoffs s kľúčom 'range'. Tieto sú informatívne a môžeš ich časom doladiť.
cutoffs:
  - range: [0, 5]
    level: "nízka"
    advice: "Priebežné sledovanie návykov."
  - range: [6, 11]
    level: "stredná"
    advice: "Zváž rozhovor o herných návykoch a vyváženosti aktivít."
  - range: [12, 16]
    level: "zvýšená"
    advice: "Odporúčaná konzultácia s odborníkom."

safety_rules: []

render:
  start_template: "gdt_form.html"
  result_template: "gdt_result.html"
